spring:
  datasource:
    HotelDB:
      url: jdbc:mysql://127.0.0.1:3306/hoteldb
      username: dev.hoteldb.username111
      password: devpassword
    FlightDB:
      url: jdbc:mysql://127.0.0.1:3306/flightdb
      username: dev.flightdb.username111
      password: devpassword
